In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Project setup is working!")

Project setup is working!

In [3]:
df = pd.read_csv(
    "../data/household_power_consumption.txt",
    sep=";",
    low_memory=False
)

df.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,16/12/2006,17:24:00,4.216,0.418,234.840,18.400,0.000,1.000,17.0
1,16/12/2006,17:25:00,5.360,0.436,233.630,23.000,0.000,1.000,16.0
2,16/12/2006,17:26:00,5.374,0.498,233.290,23.000,0.000,2.000,17.0
3,16/12/2006,17:27:00,5.388,0.502,233.740,23.000,0.000,1.000,17.0
4,16/12/2006,17:28:00,3.666,0.528,235.680,15.800,0.000,1.000,17.0

In [4]:
df.shape

(2075259, 9)

In [5]:
df.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2075259 entries, 0 to 2075258
Data columns (total 9 columns):
 #   Column                 Dtype
---  ------                 -----
 0   Date                   str
 1   Time                   str
 2   Global_active_power    str
 3   Global_reactive_power  str
 4   Voltage                str
 5   Global_intensity       str
 6   Sub_metering_1         str
 7   Sub_metering_2         str
 8   Sub_metering_3         float64
dtypes: float64(1), str(8)
memory usage: 142.5 MB

In [7]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power          0
Global_reactive_power        0
Voltage                      0
Global_intensity             0
Sub_metering_1               0
Sub_metering_2               0
Sub_metering_3           25979
dtype: int64

In [8]:
df.describe()

       Sub_metering_3
count    2.049280e+06
mean     6.458447e+00
std      8.437154e+00
min      0.000000e+00
25%      0.000000e+00
50%      1.000000e+00
75%      1.700000e+01
max      3.100000e+01

In [9]:
df.dtypes

Date                         str
Time                         str
Global_active_power          str
Global_reactive_power        str
Voltage                      str
Global_intensity             str
Sub_metering_1               str
Sub_metering_2               str
Sub_metering_3           float64
dtype: object

In [10]:
df[df["Global_active_power"] == "?"].head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
6839,21/12/2006,11:23:00,?,?,?,?,?,?,NaN
6840,21/12/2006,11:24:00,?,?,?,?,?,?,NaN
19724,30/12/2006,10:08:00,?,?,?,?,?,?,NaN
19725,30/12/2006,10:09:00,?,?,?,?,?,?,NaN
41832,14/1/2007,18:36:00,?,?,?,?,?,?,NaN

In [11]:
(df == "?").sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3               0
dtype: int64

In [12]:
df = df.replace("?", np.nan)

In [13]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [14]:
numeric_columns = [
    "Global_active_power",
    "Global_reactive_power",
    "Voltage",
    "Global_intensity",
    "Sub_metering_1",
    "Sub_metering_2",
    "Sub_metering_3"
]

df[numeric_columns] = df[numeric_columns].astype(float)

In [15]:
df.dtypes

Date                         str
Time                         str
Global_active_power      float64
Global_reactive_power    float64
Voltage                  float64
Global_intensity         float64
Sub_metering_1           float64
Sub_metering_2           float64
Sub_metering_3           float64
dtype: object

In [16]:
df.isnull().sum()

Date                         0
Time                         0
Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [17]:
df[numeric_columns].isnull().sum()

Global_active_power      25979
Global_reactive_power    25979
Voltage                  25979
Global_intensity         25979
Sub_metering_1           25979
Sub_metering_2           25979
Sub_metering_3           25979
dtype: int64

In [18]:
df[numeric_columns].isnull().any(axis=1).sum()

np.int64(25979)

In [19]:
df[numeric_columns].isnull().all(axis=1).sum()

np.int64(25979)

In [20]:
missing_rows = df[numeric_columns].isnull().all(axis=1).sum()

missing_percentage = (missing_rows / len(df)) * 100

print("Missing rows:", missing_rows)
print("Total rows:", len(df))
print("Missing percentage:", missing_percentage)

Missing rows: 25979
Total rows: 2075259
Missing percentage: 1.2518437457686005

In [21]:
missing_mask = df[numeric_columns].isnull().all(axis=1)

missing_groups = (
    missing_mask.astype(int)
    .groupby((missing_mask != missing_mask.shift()).cumsum())
    .sum()
)

missing_groups[missing_groups > 0].describe()

count      71.000000
mean      365.901408
std      1251.468043
min         1.000000
25%         1.000000
50%         1.000000
75%         3.000000
max      7226.000000
dtype: float64

In [22]:
missing_mask = df[numeric_columns].isnull().all(axis=1)

In [23]:
missing_mask.head(10)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [24]:
missing_groups[missing_groups > 0].sort_values(ascending=False).head(20)

138    7226
140    5237
14     3723
100    3305
118    3129
126    2027
104     891
32       83
78       70
34       47
70       43
84       38
26       33
88       24
38       21
72        6
102       4
98        3
24        3
2         2
dtype: int64

In [25]:
gap_lengths = missing_groups[missing_groups > 0].sort_values(ascending=False)

gap_lengths.head(10)

138    7226
140    5237
14     3723
100    3305
118    3129
126    2027
104     891
32       83
78       70
34       47
dtype: int64

In [26]:
missing_indices = df.index[missing_mask]

missing_indices[:10]

Index([6839, 6840, 19724, 19725, 41832, 61909, 98254, 98255, 142588, 190497], dtype='int64')

In [27]:
df.loc[missing_indices[:10], ["Date", "Time"]]

              Date      Time
6839    21/12/2006  11:23:00
6840    21/12/2006  11:24:00
19724   30/12/2006  10:08:00
19725   30/12/2006  10:09:00
41832    14/1/2007  18:36:00
61909    28/1/2007  17:13:00
98254    22/2/2007  22:58:00
98255    22/2/2007  22:59:00
142588   25/3/2007  17:52:00
190497   28/4/2007  00:21:00

In [28]:
df.loc[missing_indices[:10], ["Date", "Time"]]

              Date      Time
6839    21/12/2006  11:23:00
6840    21/12/2006  11:24:00
19724   30/12/2006  10:08:00
19725   30/12/2006  10:09:00
41832    14/1/2007  18:36:00
61909    28/1/2007  17:13:00
98254    22/2/2007  22:58:00
98255    22/2/2007  22:59:00
142588   25/3/2007  17:52:00
190497   28/4/2007  00:21:00

In [29]:
missing_starts = missing_mask & ~missing_mask.shift(fill_value=False)
missing_ends = missing_mask & ~missing_mask.shift(-1, fill_value=False)

start_indices = df.index[missing_starts]
end_indices = df.index[missing_ends]

gap_summary = pd.DataFrame({
    "start_index": start_indices,
    "end_index": end_indices
})

gap_summary["duration_minutes"] = (
    gap_summary["end_index"] - gap_summary["start_index"] + 1
)

gap_summary.sort_values(
    "duration_minutes",
    ascending=False
).head(10)

    start_index  end_index  duration_minutes
68      1929818    1937043              7226
69      1984952    1990188              5237
6        190497     194219              3723
49      1309386    1312690              3305
58      1616969    1620097              3129
62      1712788    1714814              2027
51      1397496    1398386               891
15       303805     303887                83
38      1043604    1043673                70
16       303897     303943                47

In [30]:
df["DateTime"] = pd.to_datetime(
    df["Date"] + " " + df["Time"],
    dayfirst=True
)

In [31]:
df[["Date", "Time", "DateTime"]].head()

         Date      Time            DateTime
0  16/12/2006  17:24:00 2006-12-16 17:24:00
1  16/12/2006  17:25:00 2006-12-16 17:25:00
2  16/12/2006  17:26:00 2006-12-16 17:26:00
3  16/12/2006  17:27:00 2006-12-16 17:27:00
4  16/12/2006  17:28:00 2006-12-16 17:28:00

In [32]:
gap_summary["start_datetime"] = df.loc[
    gap_summary["start_index"], "DateTime"
].values

gap_summary["end_datetime"] = df.loc[
    gap_summary["end_index"], "DateTime"
].values

In [33]:
gap_summary.head(10)

,start_index,end_index,duration_minutes,start_datetime,end_datetime
0,6839,6840,2,2006-12-21 11:23:00,2006-12-21 11:24:00
1,19724,19725,2,2006-12-30 10:08:00,2006-12-30 10:09:00
2,41832,41832,1,2007-01-14 18:36:00,2007-01-14 18:36:00
3,61909,61909,1,2007-01-28 17:13:00,2007-01-28 17:13:00
4,98254,98255,2,2007-02-22 22:58:00,2007-02-22 22:59:00
5,142588,142588,1,2007-03-25 17:52:00,2007-03-25 17:52:00
6,190497,194219,3723,2007-04-28 00:21:00,2007-04-30 14:23:00
7,240590,240590,1,2007-06-01 19:14:00,2007-06-01 19:14:00
8,247952,247952,1,2007-06-06 21:56:00,2007-06-06 21:56:00
9,251660,251660,1,2007-06-09 11:44:00,2007-06-09 11:44:00

In [34]:
gap_summary.sort_values(
    "duration_minutes",
    ascending=False
).head(10)

,start_index,end_index,duration_minutes,start_datetime,end_datetime
68,1929818,1937043,7226,2010-08-17 21:02:00,2010-08-22 21:27:00
69,1984952,1990188,5237,2010-09-25 03:56:00,2010-09-28 19:12:00
6,190497,194219,3723,2007-04-28 00:21:00,2007-04-30 14:23:00
49,1309386,1312690,3305,2009-06-13 00:30:00,2009-06-15 07:34:00
58,1616969,1620097,3129,2010-01-12 14:53:00,2010-01-14 19:01:00
62,1712788,1714814,2027,2010-03-20 03:52:00,2010-03-21 13:38:00
51,1397496,1398386,891,2009-08-13 05:00:00,2009-08-13 19:50:00
15,303805,303887,83,2007-07-15 16:49:00,2007-07-15 18:11:00
38,1043604,1043673,70,2008-12-10 10:48:00,2008-12-10 11:57:00
16,303897,303943,47,2007-07-15 18:21:00,2007-07-15 19:07:00

In [36]:
time_differences = df["DateTime"].diff()

time_differences.value_counts().head()

DateTime
0 days 00:01:00    2075258
Name: count, dtype: int64

In [38]:
df["DateTime"].is_monotonic_increasing

True

In [40]:
df["DateTime"].min(), df["DateTime"].max()

(Timestamp('2006-12-16 17:24:00'), Timestamp('2010-11-26 21:02:00'))

In [42]:
df["DateTime"].duplicated().sum()

np.int64(0)

In [43]:
small_gaps = gap_summary[gap_summary["duration_minutes"] <= 5]

large_gaps = gap_summary[gap_summary["duration_minutes"] > 5]

print("Small gaps:", len(small_gaps))
print("Large gaps:", len(large_gaps))

Small gaps: 55
Large gaps: 16

In [44]:
print("Rows in small gaps:", small_gaps["duration_minutes"].sum())
print("Rows in large gaps:", large_gaps["duration_minutes"].sum())

Rows in small gaps: 76
Rows in large gaps: 25903